import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "@/components/Navbar";
import Providers from "@/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Proyecto",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="flex">
            {/* Navbar ocupa un ancho fijo */}
            <Navbar />
            {/* Contenido ocupa el resto del ancho */}
            <Providers>
            <main className="flex-1 pl-[250px] py-6 max-w-[1920px]">
              {children}
            </main>
            </Providers>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}

