import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "@/components/Navbar";
import Providers from "@/Providers";
import QueryClientProviderWrapper from '@/components/QueryClientProviderWrapper'
import InactivityHandler from "@/components/InactivityHandler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Proyecto",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <QueryClientProviderWrapper>
          <div className="flex">
            <Providers>
              {session && <InactivityHandler />}
              <main className={`flex-1 ${session ? "pl-[250px] py-6 max-w-[1280px] 2xl:max-w-[1920px]" : "w-full max-w-none"} `}>
                {session && <Navbar />}
                {children}
              </main>
            </Providers>
          </div>
          </QueryClientProviderWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}